== Foibles

The following foibles have been detected with the `AVRAssist` code. Some of these _may_ be able to be fixed in future, and if so, this appendix will be updated to show that such a thing has happened. Some might not be fixable.

=== Timer 0

==== Timer 0 Overflow 
The ISR for this timer 0 overflow _cannot_ be used when compiling code within the Arduino IDE. This is down to the fact that the Arduino IDE sets up it's own ISR for this interrupt and if you (or I) define one for our own code, it will cause duplicate definition errors and as the IDE got it's version in first, we will be up that famous creek.

This problem cannot be fixed in the `AVRAssist` code as it is caused by the Arduino IDE. The problem does not occur in PlatformIO, for example, where you can define your own ISR for this interrupt without any problems.

[NOTE]
====
Redefining this interrupt in the Arduino IDE, if it actually was possible, would lead to all sorts of problems as you would be messing with the interrupt that works the `millis()` function, and from that, the `delay()` and all  the other functions that depend upon `millis()`.
====

=== Timer 1

Setting up Timer 1, to automatically toggle `OCRA` or Arduino pin `D9` does not work in the Arduino IDE. The following code:


[source,cpp]
----
#include <timer1.h>

using namespace AVRAssist;

int main() {

    // Set up the required flash rate.
    OCR1A = whatever;

    // Initialise Timer 1.
    Timer1::initialise(Timer1::MODE_CTC_OCR1A,     // Timer mode;
                       Timer1::CLK_PRESCALE_1024,  // Clock source;
                       Timer1::OC1A_TOGGLE         // Toggle OC1A on compare match;
                      );
                      

    while (1) {
        ; // do nothing.
    }
}
----

Works perfectly in PlatformIO, and the LED attached to the pin does indeed flash at the required rate. So far, so good. Converting the above for the Arduino IDE, as follows, simply toggles the LED attached to `D9` on, and leaves it on. It never flashes.


[source,cpp]
----
#include <timer1.h>

using namespace AVRAssist;

void setup() {
    // D( is required to be an output pin.
    pinMode(9, OUTPUT);
    
    // Set up the required flash rate.
    OCR1A = whatever;

    // Initialise Timer 1.
    Timer1::initialise(Timer1::MODE_CTC_OCR1A,      // Timer mode;
                       Timer1::CLK_PRESCALE_1024,   // Clock source;
                       Timer1::OC1A_TOGGLE,         // Toggle OC1A on compare match;
                       );
}

void loop() {
    // Nothing to do here...
    // Timer 1 should take care of flashing the LED on D9.
}    
----

This is an interesting foible because the `AVRAssist` code takes over the timer completely and reinitialises it to the mode given from the ground up, overwriting everything set up by the Arduino IDE. I've even gone so far as to examine the compiled assembly language for the sketch and compared it with the code in the output from PlatformIO, and they are, to all intents, identical - at least, the bits generated by the `AVRAssist` code are identical.

Time will tell if this foible can be fixed by the `AVRAssist` code or not. Watch this space.



=== Timer 2


=== Analogue Comparator

=== ???

